### ISSUE TITLE
请问在执行tutorial的过程中helm install dgs-u2i dgs/dgs报错是为什么

### ISSUE THREAD

**Issue by Homura2333** [alibaba/graph-learn#241]
执行到这一步：
<img width="651" alt="image" src="https://user-images.githubusercontent.com/39360166/205922743-0f30ebcc-1d3b-48d1-b630-e203bfbdc9ee.png">

我的输入是：
`helm install dgs-u2i DGS/dgs     --set frontend.ingressHostName="dynamic-graph-service.info"     --set-file graphSchema=./conf/u2i/schema.u2i.json     --set kafka.dl2spl.brokers=[localhost:9092]     --set kafka.dl2spl.topic="record-batches"     --set kafka.dl2spl.partitions=4     --set kafka.spl2srv.brokers=[localhost:9092]     --set kafka.spl2srv.topic="sample-batches"     --set kafka.spl2srv.partitions=4     --set glog.toConsole=true
`

报的错误是：
`Error: INSTALLATION FAILED: template: dgs/templates/configmap.yaml:46:27: executing "dgs/templates/configmap.yaml" at <.Values.kafka.dl2spl.brokers>: range can't iterate over [localhost:9092]
`
错误中的yaml文件相关内容如下：
```
 kafka:
      dl2spl:
        servers:
          {{- range .Values.kafka.dl2spl.brokers }}
          - {{ . | quote }}
          {{- end }}
        topic: {{ .Values.kafka.dl2spl.topic | quote }}
        partitions: {{ int .Values.kafka.dl2spl.partitions }}
```
请问是为什么？我应该输入什么呢？
